### ISSUE TITLE
Window events

### ISSUE THREAD

**Issue by shakna-israel** [victorqribeiro/fos#5]
Is there a way to tell:

* If a window has focus?
* If a window has closed?

I'm basically considering sticking a video player inside a window, but I need to handle a couple events for the player, like pausing and stopping if the user puts it out of focus or closes it.

**Comment by victorqribeiro** [comment]
you can tell if a fos-window is closed by it's style: document.querySelector('fos-window').style.display == "block"
and you can tell if a fos-window is on top of all the others (focused) if it's document.querySelector('fos-window').style.zIndex == 999.

I was adding stuff to this framework as I was needing, so later on I can add this attributes to the component so you don't have to look at their style
