### ISSUE TITLE
Help for duplicate

### ISSUE THREAD

**Issue by ReyW0** [victorqribeiro/fos#6]
Hi,
I'm trying to reproduce this desktop : 
![Mission Scientifique 1 SCP-054 Nymphe aquatique_Moment](https://user-images.githubusercontent.com/46190911/148692970-bef3b4ff-265c-4599-a5db-23f27a664efc.jpg)

I don't know how to make date time (down-right). And how to make a twice fos-bar in up of screen. Help ?

**Comment by victorqribeiro** [comment]
Sorry I couldn't help right away.
